general:
  startup_commands: ['shell-exec zebar']
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: true
    trigger: 'monitor_focus'

  hide_method: 'cloak'
  show_all_in_taskbar: false

gaps:
  scale_with_dpi: true
  inner_gap: '15px'
  outer_gap:
    top: '45px'
    right: '15px'
    bottom: '15px'
    left: '15px'

window_effects:
  focused_window:
    border:
      enabled: true
      color: '#FFFFFF'

    hide_title_bar:
      enabled: false

    corner_style:
      enabled: true
      style: 'rounded'

    transparency:
      enabled: true
      opacity: '0.95'

  other_windows:
    border:
      enabled: true
      color: '#545454'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: 'square'
    transparency:
      enabled: true
      opacity: '0.95'

window_behavior:
  initial_state: 'tiling'
  state_defaults:
    floating:
      centered: true
      shown_on_top: false

    fullscreen:
      maximized: false
      shown_on_top: false

workspaces:
  - name: '1'
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'

window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['alt+h', 'alt+left']
  - commands: ['focus --direction right']
    bindings: ['alt+l', 'alt+right']
  - commands: ['focus --direction up']
    bindings: ['alt+k', 'alt+up']
  - commands: ['focus --direction down']
    bindings: ['alt+j', 'alt+down']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['alt+shift+h', 'alt+shift+left']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l', 'alt+shift+right']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k', 'alt+shift+up']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j', 'alt+shift+down']

  # Resize focused window by a percentage or pixel amount.
  - commands: ['resize --width -2%']
    bindings: ['alt+u']
  - commands: ['resize --width +2%']
    bindings: ['alt+p']
  - commands: ['resize --height +2%']
    bindings: ['alt+o']
  - commands: ['resize --height -2%']
    bindings: ['alt+i']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  # Change the focused window to be tiling.
  - commands: ['toggle-tiling']
    bindings: ['alt+t']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['alt+m']

  # Close focused window.
  - commands: ['close']
    bindings: ['alt+shift+q']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['alt+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ['shell-exec wt']
    bindings: ['alt+enter']

  # # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['alt+q']
  - commands: ['focus --workspace 2']
    bindings: ['alt+w']
  - commands: ['focus --workspace 3']
    bindings: ['alt+e']
  - commands: ['focus --workspace 4']
  #   bindings: ['alt+4']
  # - commands: ['focus --workspace 5']
  #   bindings: ['alt+5']
  # - commands: ['focus --workspace 6']
  #   bindings: ['alt+6']
  # - commands: ['focus --workspace 7']
  #   bindings: ['alt+7']
  # - commands: ['focus --workspace 8']
  #   bindings: ['alt+8']
  # - commands: ['focus --workspace 9']
  #   bindings: ['alt+9']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['alt+shift+z']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['alt+shift+x']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['alt+shift+c']
  # - commands: ['move --workspace 4', 'focus --workspace 4']
  #   bindings: ['alt+shift+4']
  # - commands: ['move --workspace 5', 'focus --workspace 5']
  #   bindings: ['alt+shift+5']
  # - commands: ['move --workspace 6', 'focus --workspace 6']
  #   bindings: ['alt+shift+6']
  # - commands: ['move --workspace 7', 'focus --workspace 7']
  #   bindings: ['alt+shift+7']
  # - commands: ['move --workspace 8', 'focus --workspace 8']
  #   bindings: ['alt+shift+8']
  # - commands: ['move --workspace 9', 'focus --workspace 9']
  #   bindings: ['alt+shift+9']
